### ISSUE TITLE
Support a different installation method

### ISSUE THREAD

**Issue by sotojuan** [stevemao/diff-so-fancy#14]
npm is fine for us who do a lot of JS, but it's not convenient for people who don't. This project uses no JavaScript, so it really has no hard dependency on npm.

It'd be great if you could install this in a different, more common way.

**Comment by mirceal** [comment]
xcopy?

**Comment by aziz** [comment]
I agree. npm feels wierd for distributing a bunch of shell scripts. I feed sick in my stomach specially because it reminds of those people who are attacking npm because it contains a whole bunch of shit.

But do you have any suggestion that is as cross platform and as easy as npm for distributing these scripts, making them executable and put them on the path?

**Comment by rjc** [comment]
The content is on `GitHub` so the "distribution method" is `git` itself, no?

Installation? Err... `cp` or `ln` - `install` at most. `make` would have been an overkill :^)

**Comment by paulirish** [comment]
I just added manual install instructions: https://github.com/stevemao/diff-so-fancy/blob/master/readme.md#manual-install

They could probably still use some work... 

What should I change about them?

**Comment by paulirish** [comment]
My [previous install directions](https://github.com/paulirish/dotfiles/blob/master/bin/diff-so-fancy#L23-L24) recommended dropping this into `~/bin` under the assumption people had that in their PATH.  

@sotojuan @aziz Should I spell that out or the current wording is decent?

Current wording, for reference: 

> ### Manual Install
> If you want, you can choose to install manually:

> * Grab the two scripts (`diff-highlight` and `diff-so-fancy`) via either downloading or cloning the repo.
> * Place them in a location that is in your `PATH`.
> * Set up the git `core.pager` config, as described above

**Comment by aziz** [comment]
For me as Mac and Linux user It's pretty clear. I don't know how a Windows user feels about it. I still can't remember how to manipulate the PATH in Windows :cold_sweat:

**Comment by paulirish** [comment]
Cool. @sotojuan I'll wait until you give the :+1: before we close this issue.

**Comment by sotojuan** [comment]
Looks good to me! Thanks for the quick response 👍🏼.

**Comment by paulirish** [comment]
cheers
