### ISSUE TITLE
why it is a NPM install?

### ISSUE THREAD

**Issue by cht8687** [stevemao/diff-so-fancy#15]

**Comment by stevemao** [comment]
Me and Paul also answered this on HN.
I see a lot of projects that's written in other languages on npm, especially bash. Substack even published c code to npm. I think it makes the script more accessible especially for nodejs users. I don't mind publishing it to other package mangers.
Me myself is a JavaScript developer, so I started with npm. Contributions welcome for publishing it to other package managers.

**Comment by stevemao** [comment]
I hope it makes sense. Closing now.
