### ISSUE TITLE
No way of showing added or removed empty lines?

### ISSUE THREAD

**Issue by maxpblum** [stevemao/diff-so-fancy#16]
Thanks so much for this awesome tool! Is there a way to make it show added or removed empty lines? I see the added space from the new lines in my diff, but they aren't highlighted at all. (I installed it on OS X, following your instructions to a tee, including all of your suggested changes to my Git config.)

**Comment by noscript** [comment]
take a look at #11

**Comment by maxpblum** [comment]
Amazing!
