### ISSUE TITLE
Incorrectly highlighted lines on Windows

### ISSUE THREAD

**Issue by simevidas** [stevemao/diff-so-fancy#17]
I've set up the tool using the instructions from the README (npm install, then set core.pager value). I've run a test diff and the *first code line of each file* is incorrectly highlighted and colored:

![capture](https://cloud.githubusercontent.com/assets/716405/12931455/3f61118c-cf7e-11e5-97b1-408ded3c6543.PNG)

Also, the headers are white instead of yellow, but that's a minor issue.

My environment: Windows 10, Cmder console (but issue also occurs in PowerShell), default Git for Windows installer.

**Comment by noscript** [comment]
Try removing `colorize_context_line`:

```diff
-cat $input | format_diff_header |  colorize_context_line | strip_leading_symbols
+cat $input | format_diff_header |  strip_leading_symbols
```

@stevemao what `colorize_context_line` is actually for? Can we colorize the context part via `color.diff.frag`?

```
git config --global color.diff.frag cyan
```

**Comment by stevemao** [comment]
CC @paulirish

**Comment by simevidas** [comment]
@noscript Thanks. Looks fine now, after removing `colorize_context_line`:

![capture](https://cloud.githubusercontent.com/assets/716405/12932829/362cade0-cf85-11e5-96d8-37cf4cee448e.PNG)

**Comment by stevemao** [comment]
@noscript `colorize_context_line` is probably just to make it prettier.

**Comment by paulirish** [comment]
tbh colorizing the context line is totally optional. i just wanted the foreground color of the context line to be different than the default (white) text.

**Comment by stevemao** [comment]
@simevidas Can you try #56?

**Comment by simevidas** [comment]
@stevemao The background’s gone (good!), but the font color is now magenta instead of white:

![foo](https://cloud.githubusercontent.com/assets/716405/13029363/951a6092-d28a-11e5-89df-8e970618e374.png)

**Comment by paulirish** [comment]
@simevidas ya. that's intentional. Purple'd so that you can differentiate the context vs the plain code. That's what's intended.

**Comment by taeguk** [comment]
I encountered same issue in lastest master.
I also use Cmder console in windows 10, too.
