### ISSUE TITLE
readme instructions for setting global config misleading

### ISSUE THREAD

**Issue by BMayneFactual** [stevemao/diff-so-fancy#18]
I'm not an expert on git config manual editing, but adding 

`git config --global core.pager "diff-highlight | diff-so-fancy | less --tabs=1,5 -R"` to my git config on mac was invalid. 

Running `git config --global core.pager "diff-highlight | diff-so-fancy | less --tabs=1,5 -R"`, however, added this line under core

```
[core]
	pager = diff-highlight | diff-so-fancy | less --tabs=1,5 -R
```

**Comment by noscript** [comment]
Indeed, it's a bit confusing.

**Comment by paulirish** [comment]
good call. my bad :)
