### ISSUE TITLE
Have a way to switch between old way of `git diff` and the new one

### ISSUE THREAD

**Issue by prat0318** [stevemao/diff-so-fancy#22]
Sometimes, i do want to get a patch from `git diff`. Is there an easy way to do that once i have turned on `diff-so-fancy` git config?

**Comment by stevemao** [comment]
```
$ git config --global core.pager less
```

**Comment by paulirish** [comment]
There's probably a less destructive way. I'm curious as well. Let's document a decent solution in the readme

**Comment by paulirish** [comment]
Easy enough!  `git --no-pager diff`  :)
