### ISSUE TITLE
Can't use the arrow keys to scroll up/down during the diff

### ISSUE THREAD

**Issue by stringbeans** [stevemao/diff-so-fancy#26]
Not sure if this is even fixable since you're piping the output but it would be nice :)

**Comment by stevemao** [comment]
Doesn't happen on my machine. I believe it's related to your [`core.pager`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)

**Comment by chubas** [comment]
Same issue, I lose paging capabilities when using it. Workaround is to add a ` | less -R` on the git alias.
My pager is set to `less -FRSX` which seems to be pretty standard.

**Comment by stevemao** [comment]
@chubas @stringbeans The readme already mentions `git config --global core.pager "diff-so-fancy | less --tabs=1,5 -R"`, this should work?

**Comment by gfpacheco** [comment]
I fixed it by removing the `X` from the less flags on the instructions:

    git config --global pager.diff "diff-so-fancy | less --tabs=1,5 -RF"
    git config --global pager.show "diff-so-fancy | less --tabs=1,5 -RF"
