### ISSUE TITLE
colors not showing up

### ISSUE THREAD

**Issue by tnguyen14** [stevemao/diff-so-fancy#3]
I added the colors for `diff-highlight` in my `.gitconfig` as instructed, however the output of `git diff | diff-highlight` does not output any colors. 

Could there be something that I am missing here?

**Comment by stevemao** [comment]
`git diff --color | diff-highlight` should work.
But I use `git config --global core.pager "diff-highlight | diff-so-fancy | less -r"` so any diff related commands will use `diff-so-fancy` :)

**Comment by tnguyen14** [comment]
Thank you. Using the `--color` flag worked.

When I tried the config to setting `core.pager` as you suggested, I see an issue with indentation being off, as such:

```diff
@@ -68,6 +68,7 @@
        whitespace = space-before-tab,indent-with-non-tab,trailing-space
        quotepath = false
        editor = vim
  pager = diff-highlight | diff-so-fancy | less -r
        # editor = subl -n -w
```

**Comment by stevemao** [comment]
Can you open another issue if it's not related to your original one? It would be helpful if you could include a screenshot. Thanks.
