### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by paulirish** [stevemao/diff-so-fancy#32]
I think it's time for us to add proper unit tests.

I haven't seen a test suite for a project like this before, but it shouldnt be too bad. I'm thinking a folder of input text files, with ANSI escapes and all. And a folder of expected output. Seem right?

Is there a test runner that'd work well for us?

**Comment by stevemao** [comment]
:+1: , to **hard** to test manually!

**Comment by paulirish** [comment]
Ah, I now remember https://github.com/sstephenson/bats This seems close to ideal. :)

**Comment by paulirish** [comment]
I attempted to get this going, but it's a bit tougher than expected.

For anyone curious, this points to the most mature assertion set for use with bats: https://github.com/sstephenson/bats/pull/110#issuecomment-182158121

I believe that Bats struggles with the combination of multiline output, ansi colors and empty newlines. As such, I haven't been able to target specific lines in the output, only just fuzzy partial matches against the whole thing.
