### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by stevemao** [stevemao/diff-so-fancy#40]
We've done an **amazing** job so far! Thank you everyone :smile: 

* readme: clarity on diff-highlight & other readability improvements ([1b4194a](https://github.com/stevemao/diff-so-fancy/commit/1b4194a))
* readme: manual install ([21ffc64](https://github.com/stevemao/diff-so-fancy/commit/21ffc64))
*  diff_highlight should be relative to the source instead of cwd ([ded0b09](https://github.com/stevemao/diff-so-fancy/commit/ded0b09))
* add comments on finding the deps ([feceb50](https://github.com/stevemao/diff-so-fancy/commit/feceb50))
* Add git alias usage to docs ([5035027](https://github.com/stevemao/diff-so-fancy/commit/5035027))
* Add in diff-highlight's link ([459e8e8](https://github.com/stevemao/diff-so-fancy/commit/459e8e8))
* add in License MIT in Readme ([1d132c4](https://github.com/stevemao/diff-so-fancy/commit/1d132c4))
* Define shorter `dsf` alias in docs ([bb427e8](https://github.com/stevemao/diff-so-fancy/commit/bb427e8))
* depend on local diff-highlight. ([d614817](https://github.com/stevemao/diff-so-fancy/commit/d614817))
* Detect gsed and use it if it exists ([e0fa502](https://github.com/stevemao/diff-so-fancy/commit/e0fa502))
* Fixes path detection for nvm users ([967fb0b](https://github.com/stevemao/diff-so-fancy/commit/967fb0b))
* Fixes readme for gnu-sed ([e372403](https://github.com/stevemao/diff-so-fancy/commit/e372403))
* License change to MIT ([ed9e3cc](https://github.com/stevemao/diff-so-fancy/commit/ed9e3cc))
* link git contrib and change diff-highlight link to it's folder (to view readme) ([deddd80](https://github.com/stevemao/diff-so-fancy/commit/deddd80))
* mark empty newlines ([5c3aa39](https://github.com/stevemao/diff-so-fancy/commit/5c3aa39))
* Missing . in sentence ([c584da0](https://github.com/stevemao/diff-so-fancy/commit/c584da0))
* prefer a global diff-highlight, but fallback to our local copy ([8e5da94](https://github.com/stevemao/diff-so-fancy/commit/8e5da94))
* readme. easy bypass of diff-so-fancy ([519568c](https://github.com/stevemao/diff-so-fancy/commit/519568c)), closes [#22](https://github.com/stevemao/diff-so-fancy/issues/22)
* set tab stops for less ([fc306e2](https://github.com/stevemao/diff-so-fancy/commit/fc306e2))
* Update readme.md ([7bcda36](https://github.com/stevemao/diff-so-fancy/commit/7bcda36))

Is there anything we missing before a new release?

**Comment by aziz** [comment]
let's release more often.

**Comment by stevemao** [comment]
released now :)

**Comment by vanniktech** [comment]
How can I update it to the latest version?

**Comment by stevemao** [comment]
`npm install -g diff-so-fancy`

**Comment by stevemao** [comment]
Pretty much just reinstall it.

**Comment by vanniktech** [comment]
I tried this one already and I got:

> npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "install" "-g" "diff-so-fancy"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path /usr/local/bin/diff-highlight
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/diff-highlight: ../lib/node_modules/diff-so-fancy/diff-highlight symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/diff-highlight
npm ERR! Move it away, and try again.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nik/dev/familonet-android-client/npm-debug.log

**Comment by stevemao** [comment]
That's an `npm` issue. I suggest you try `sudo` and search for `npm help.
