### ISSUE TITLE
Inline changes not inline

### ISSUE THREAD

**Issue by JacobEvelyn** [stevemao/diff-so-fancy#41]
I'm not able to see inline changes as advertised in the README:

<img width="303" alt="screen shot 2016-02-11 at 7 51 11 am" src="https://cloud.githubusercontent.com/assets/1114569/12976762/6a064788-d094-11e5-964a-232d617b6266.png">

I believe this should be just one line, but it's showing up as two. I'm on OS X using zsh as my shell if that matters.

**Comment by paulirish** [comment]
@jacobevelyn do me a favor:

```sh
git --no-pager diff | pbcopy
```

and paste the results into a comment here.

**Comment by mikezuff** [comment]
I had the same symptom. npm had installed an older version of diff-so-fancy. Downloading directly fixed it.

**Comment by stevemao** [comment]
https://github.com/stevemao/diff-so-fancy/issues/40

**Comment by stevemao** [comment]
I made a new release. Let me know if you still have the same issue and we can reopen.

**Comment by JacobEvelyn** [comment]
@stevemao sorry for the delay. I just downloaded the newest version from `npm` and still have the same behavior. Here are the relevant lines from the `pbcopy` you asked for:

```
-	<string>1.14</string>
+	<string>1.13</string>
```
