### ISSUE TITLE
Current git config instructions clobbers `git log`

### ISSUE THREAD

**Issue by jamischarles** [stevemao/diff-so-fancy#42]
`git config --global core.pager "diff-so-fancy | less --tabs=1,5 -R"`

This highjacks things like `git log`, and other commands locally for me. Is there a non-destructive way of doing this? If not, I'd suggest showing how to alias it in bash instead of adding it to the gitconfig.

**Comment by noscript** [comment]
Use `diff-so-fancy` for `show` and `diff` pagers only:
```
git config --global pager.diff "diff-so-fancy | less --tabs=1,5 -R"
git config --global pager.show "diff-so-fancy | less --tabs=1,5 -R"
```

**Comment by jamischarles** [comment]
:tada:
