### ISSUE TITLE
Remove the duplicate line

### ISSUE THREAD

**Issue by haoyangnz** [stevemao/diff-so-fancy#43]
When text is added/removed in a line, why not just show the added/removed part instead of a removed original line and a new line?

**Comment by noscript** [comment]
Use `git diff --color-words`.

**Comment by haoyangnz** [comment]
Would be good if this was in the readme

**Comment by noscript** [comment]
It's in git manual. Readme cannot cover every git use case.

**Comment by haoyangnz** [comment]
Ah sorry - I thought it was a diff-so-fancy flag. Wasn't aware of the git flag.

**Comment by haoyangnz** [comment]
--color-words doesn't actually attempt to detect word changes, it just joins the deleted line and the added line. I was hoping diff-so-fancy attempts to detect the portion of text that was modified.

Would this be considered or am I better off doing it in a fork?

**Comment by noscript** [comment]
You are certainly welcome to do a pull request.

**Comment by kergoth** [comment]
--color-words destroys the changed word highlighting done by diff-highlight. Am I missing something? How can you get the joined removed/added lines in a modification case while retaining the nice diff-so-fancy/diff-highlight highlighting?

**Comment by paulirish** [comment]
Agree, as @kergoth says, `--color-words` an alternative to using diff-highlight.  In my experience, it provides an inferior view of the changes. 

It shines when diff'ing prose, but is generally worse for code. It's something I use on occasion, and it should be left to the user to decide.  (Until diff-so-fancy starts picking the best diff algorithm/tokenizing based on the text contents :)

We could add a mention to the readme, but it'd be more about general tips on getting useful diffs.
