### ISSUE TITLE
Highlight works in diff-highlight, does nothing in diff-so-fancy

### ISSUE THREAD

**Issue by teroyks** [stevemao/diff-so-fancy#45]
Any idea why diff-so-fancy fails to highlight changes when diff-highlight works just fine (see attached screenshot)? Right after installing (with npm), no changes to default configs. (I'm on Centos 6.7)

![screen shot 2016-02-12 at 11 44 18](https://cloud.githubusercontent.com/assets/2240765/13003582/0901fc8e-d17f-11e5-94e1-530e668e5d56.png)

**Comment by stevemao** [comment]
The readme here is out of sync with the released one. Let me make a release soon.

**Comment by teroyks** [comment]
The culprit seems to be the npm-installed version. The latest version works.
