### ISSUE TITLE
Join forces with diff-ss

### ISSUE THREAD

**Issue by djui** [stevemao/diff-so-fancy#48]
[diff-ss](https://github.com/djui/diff-ss) is the side-by-side diff version of git diff. It would be nice to join both (all three together with `diff-highlight`) to make the ultimate terminal diffing experience! :sunglasses: 

Disclaimer: of course this is a shameless plug from the author...

**Comment by stevemao** [comment]
Personally I don't like side by side diff. I never use GitHub's split view.

**Comment by djui** [comment]
Alright, no worries.
