### ISSUE TITLE
clean up inline docs from so-fancy script

### ISSUE THREAD

**Issue by paulirish** [stevemao/diff-so-fancy#5]
Now that it's in a real readme, maybe you want to clean out the inline docs. 

you can definitely remove the TODO about npm, since you did that. :)

**Comment by paulirish** [comment]
ooh! and thanks for adding me to the repo!

 didn't realize that, so i just committed a change to the readme, when i thought it was going to make a PR. :)

**Comment by stevemao** [comment]
Sure, this is your project. Your also the owner on npm :)
