### ISSUE TITLE
Hard dependency on diff-highlight from diff-so-fancy 

### ISSUE THREAD

**Issue by paulirish** [stevemao/diff-so-fancy#6]
Maybe we should just depend on `diff-highlight` from inside of `diff-so-fancy`.

That would mean people instead configure it with `git diff | diff-so-fancy` directly.

If `diff-highlight` isn't found, we could just pass through the `stdin` and perhaps issue a warning that says "hey you're missing diff-highlight bud"

Seems a little more user-friendly. wdyt?

**Comment by stevemao** [comment]
:+1: Ideally I don't wanna maintain `diff-highlight`. Wish we could reference that dependency from the official git repo somehow.

**Comment by paulirish** [comment]
yeah understood.
i dont know of an easy way.

I just explored trying to use diff-highlight from the machine, but i'm not sure how to do that on non-homebrew installs.

tbh, the simplest looks to be just writing a stupid script to pull the latest diff-highlight from the git repo every once in a while. it doesnt change a lot so no biggie.

**Comment by paulirish** [comment]
here's my proposal in #13

**Comment by stevemao** [comment]
Found a problem in #13 (sorry didn't find it earlier). We assume the `diff_highlight` path is `./third_party/diff-highlight/diff-highlight` which might not be the case. `npm link` won't work. Documentation
> Grab the two scripts (diff-highlight and diff-so-fancy) via either downloading or cloning the repo.
Place them in a location that is in your PATH.

Is incorrect.
We don't really know the path of our hard dependency `diff-highlight`

**Comment by stevemao** [comment]
Maybe we just use `which diff-highlight`?

**Comment by xixixao** [comment]
Why not just let people install and pipe themselves?

```
git diff --color | diff-highlight | diff-so-fancy

**Comment by stevemao** [comment]
We want to load diff-hight internally in diff-so-fancy.
