### ISSUE TITLE
Encoding issue or broken sed command

### ISSUE THREAD

**Issue by aziz** [stevemao/diff-so-fancy#7]
<img width="231" alt="screen shot 2016-02-08 at 1 45 13 pm" src="https://cloud.githubusercontent.com/assets/3202/12885973/788ea5c4-ce6a-11e5-85eb-2720a00bd7ad.png">

I tried many other fonts in my iTerm terminal. 

Interestingly, in Mac Terminal I get an error like this: 

```
sed: -e expression #1, char 211: unterminated `s' command
sed: -e expression #1, char 197: unterminated `s' command
```

**Comment by noscript** [comment]
Sed errors aren't related to the encoding. To fix encoding issue I suggest to switch from `tr` to `sed` in `print_horizontal_rule()`:

```diff
 print_horizontal_rule () {
-        printf "%$(tput cols)s\n"|tr " " "─"
+        printf "%$(tput cols)s\n"|sed 's/ /─/g'
 }

**Comment by aziz** [comment]
I confirm that this change proposed by @noscript  has actually fixed my issue. making it into a pull request.

**Comment by stevemao** [comment]
@noscript What's your npm name? I'll add you :)

**Comment by noscript** [comment]
~noscript :) just registered

**Comment by stevemao** [comment]
Thanks all for your contribution!
