### ISSUE TITLE
indentation seems to be off when configuring the pager

### ISSUE THREAD

**Issue by tnguyen14** [stevemao/diff-so-fancy#9]
When I use the pager config for any diff related command (`git config --global core.pager "diff-highlight | diff-so-fancy | less -r"`), the indentation seems to be off.

<img width="715" alt="screen shot 2016-02-08 at 8 23 46 am" src="https://cloud.githubusercontent.com/assets/1652595/12887997/67d85838-ce3d-11e5-86f7-672e7b8ed235.png">

This does not seem to happen if I just do `git diff | diff-highlight | diff-so-fancy`.

**Comment by noscript** [comment]
You need to tell less the tab stops:

```diff
-git config --global core.pager "diff-highlight | diff-so-fancy | less -r"
+git config --global core.pager "diff-highlight | diff-so-fancy | less --tabs=1,5 -R"
```

**Comment by tnguyen14** [comment]
@noscript that solved the issue. Thank you.

**Comment by stevemao** [comment]
@noscript should we change the readme?

**Comment by noscript** [comment]
just did :)

**Comment by stevemao** [comment]
Thanks :)
